from . import crm_lead
from . import document
from . import module_array
from . import monthly_usages
from . import project_project
from . import res_partner
from . import crm_market
from . import utm
from . import disposition
from . import project_milestone
from . import folder
